### ISSUE TITLE
How to call “step” function in mjsim.pyx

### ISSUE THREAD

**Issue by KindleKin** [nikolavulin/tactile_intrinsic_motivation#1]
I got an unexpected error "TypeError: cannot unpack non-iterable NoneType object" at line 72 in robot_env.py when I run code.
I found that I didn't call mjsim.pyx successfully, so the code "self.sim.step()" return None which is not match with the "force_left, force_right, _, energy_return "
Here is the broken code:
`force_left, force_right, _, energy_return = self.sim.step()`
Is there any friend could help me fix it?

**Comment by sammychristen** [comment]
Hi

You need to download mujoco-py from the official repository [https://github.com/openai/mujoco-py](https://github.com/openai/mujoco-py).
Then you need to replace the file mjsim.pyx in mujoco-py with this file [https://github.com/nikolavulin/tactile_intrinsic_motivation/blob/master/MuJoCo/mjsim.pyx](https://github.com/nikolavulin/tactile_intrinsic_motivation/blob/master/MuJoCo/mjsim.pyx).

You can then install mujoco-py via 
`pip install -e .`
or
`python setup.py install`

This should fix the error.

**Comment by KindleKin** [comment]
> Hi
> 
> You need to download mujoco-py from the official repository https://github.com/openai/mujoco-py.
> Then you need to replace the file mjsim.pyx in mujoco-py with this file https://github.com/nikolavulin/tactile_intrinsic_motivation/blob/master/MuJoCo/mjsim.pyx.
> 
> You can then install mujoco-py via
> `pip install -e .`
> or
> `python setup.py install`
> 
> This should fix the error.

Thanks for your reply.

I have tested the way as you describe ever before, however, the error I got haven't change.

Is this related to my running environment which is windows?

**Comment by sammychristen** [comment]
It should not matter that you are running on Windows.

The important thing is that mujoco-py gets cythonized with the replaced file. 

Are you running in a virtual environment and have you made sure there are no other mujoco-py installations in the background that could overwrite the source installation? 

First install both the gym folder and the algorithm folder, then make sure that if you are running python and `import mujoco_py`, there is no package found (if there is, you need to uninstall mujoco-py). Then, install mujoco-py with the replaced file. 
If you run it in python:

`import mujoco_py`
`print(mujoco_py.__file__)`

It should i) cythonize mujoco-py there first time you load it and ii) point you to the local path to where you stored the mujoco_py source code.

Hope this helps.

**Comment by KindleKin** [comment]
I did run it in a conda environment.

I did uninstall mujoco-py again, I got error “no module named 'mujoco_py'” when I `import mujoco_py`.

Then I use `pip install -e .` to install mujoco-py again, and when I run `import mujoco_py` and `print(mujoco_py.__file__)`, I got correct path of my mujoco source file.

**But I still got same error** "TypeError: cannot unpack non-iterable NoneType object", when I run random action wih following code:
`env = gym.make('FetchPAPSensors-v1')
  while True:
      observation = env.reset()
      for t in range(100):
          env.render()
          action = env.action_space.sample()
          observation, reward, done, info = env.step(action)
          print(observation)
          if done:
              print("Episode finished after {} timesteps".format(t+1))
              break`

How do I know whether the mujoco-py gets cythonized?

I really appreciate that you spend time helpingn me.

**Comment by KindleKin** [comment]
> It should not matter that you are running on Windows.
> 
> The important thing is that mujoco-py gets cythonized with the replaced file.
> 
> Are you running in a virtual environment and have you made sure there are no other mujoco-py installations in the background that could overwrite the source installation?
> 
> First install both the gym folder and the algorithm folder, then make sure that if you are running python and `import mujoco_py`, there is no package found (if there is, you need to uninstall mujoco-py). Then, install mujoco-py with the replaced file.
> If you run it in python:
> 
> `import mujoco_py`
> `print(mujoco_py.__file__)`
> 
> It should i) cythonize mujoco-py there first time you load it and ii) point you to the local path to where you stored the mujoco_py source code.
> 
> Hope this helps.

I did run it in a conda environment.

I did uninstall mujoco-py again, I got error “no module named 'mujoco_py'” when I import mujoco_py.

Then I use pip install -e . to install mujoco-py again, and when I run import mujoco_py and print(mujoco_py.__file__), I got correct path of my mujoco source file.

But I still got same error "TypeError: cannot unpack non-iterable NoneType object", when I run random action wih following code:
```
env = gym.make('FetchPAPSensors-v1')
while True:
  observation = env.reset() 
  for t in range(100):
    env.render() 
    action = env.action_space.sample() 
    observation, reward, done, info = env.step(action)
    print(observation) 
    if done: 
      print("Episode finished after {} timesteps".format(t+1)) 
      break
```

How do I know whether the mujoco-py gets cythonized?

I really appreciate that you spend time helpingn me.

**Comment by KindleKin** [comment]
> It should not matter that you are running on Windows.
> 
> The important thing is that mujoco-py gets cythonized with the replaced file.
> 
> Are you running in a virtual environment and have you made sure there are no other mujoco-py installations in the background that could overwrite the source installation?
> 
> First install both the gym folder and the algorithm folder, then make sure that if you are running python and `import mujoco_py`, there is no package found (if there is, you need to uninstall mujoco-py). Then, install mujoco-py with the replaced file.
> If you run it in python:
> 
> `import mujoco_py`
> `print(mujoco_py.__file__)`
> 
> It should i) cythonize mujoco-py there first time you load it and ii) point you to the local path to where you stored the mujoco_py source code.
> 
> Hope this helps.

I did run it in a conda environment.

I did uninstall mujoco-py again, I got error “no module named 'mujoco_py'” when I import mujoco_py.

Then I use pip install -e . to install mujoco-py again, and when I run import mujoco_py and print(mujoco_py.file), I got correct path of my mujoco source file.

**But I still got same error** "TypeError: cannot unpack non-iterable NoneType object", when I run random action wih following code:

```
env = gym.make('FetchPAPSensors-v1')
while True:
  observation = env.reset() 
  for t in range(100):
    env.render() 
    action = env.action_space.sample() 
    observation, reward, done, info = env.step(action)
    print(observation) 
    if done: 
      print("Episode finished after {} timesteps".format(t+1)) 
      break
```
How do I know whether the mujoco-py gets cythonized?

I really appreciate that you spend time helping me.

**Comment by sammychristen** [comment]
If you `import mujoco_py` for the first time, it should say something like:
`[1/1] Cythonizing path_to_mujoco_py/mujoco-py/mujoco_py/cymj.pyx
running build_ext
building 'mujoco_py.cymj' extension
`

Did you see this when you ran it?

This happens only once if you install mujoco-py from source and the generated files are put into the folder path_to_mujoco_py/mujoco-py/mujoco_py/generated/.
So you need to either clear the "generated" folder  to only contain the original files or download mujoco-py again, replace the mjsim.pyx file and install it.

The problem originates because the mjsim.pyx file with the replaced step function at line 115-141 is not being cythonized.

**Comment by KindleKin** [comment]
> If you `import mujoco_py` for the first time, it should say something like:
> `[1/1] Cythonizing path_to_mujoco_py/mujoco-py/mujoco_py/cymj.pyx running build_ext building 'mujoco_py.cymj' extension `
> 
> Did you see this when you ran it?
> 
> This happens only once if you install mujoco-py from source and the generated files are put into the folder path_to_mujoco_py/mujoco-py/mujoco_py/generated/.
> So you need to either clear the "generated" folder to only contain the original files or download mujoco-py again, replace the mjsim.pyx file and install it.
> 
> The problem originates because the mjsim.pyx file with the replaced step function at line 115-141 is not being cythonized.

Oh, Thank you bro.

**It works!**

**But** I discard Windows version, because I have strugled with the error 
`distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`
for the whole day, which occurd after I `import mujoco_py`.

Do you know how to fix it?

Whatever, it works on Ubuntu as follow your notion now.

Thank you very much!

**Comment by sammychristen** [comment]
Hi

Glad to hear it worked out. 

I'm not a Windows user, so I can't help you there. Also, this seems to be a mujoco-py related issue and not specific to our code. I recommend you to browse through the mujoco-py forum for a potential solution. A quick search showed this: https://github.com/openai/mujoco-py/issues/253.

Generally, I've found the mujoco-py package to be quite fragile, so it can take quite some time to get it to work in specific settings.

**Comment by KindleKin** [comment]
> Hi
> 
> Glad to hear it worked out.
> 
> I'm not a Windows user, so I can't help you there. Also, this seems to be a mujoco-py related issue and not specific to our code. I recommend you to browse through the mujoco-py forum for a potential solution. A quick search showed this: [openai/mujoco-py#253](https://github.com/openai/mujoco-py/issues/253).
> 
> Generally, I've found the mujoco-py package to be quite fragile, so it can take quite some time to get it to work in specific settings.

OK, thanks for your suggestion very much.

Btw, have you ever thought about embracing pybullet?

**Comment by sammychristen** [comment]
Yes, of course, it is a decent and open-source alternative.

I guess it's a matter of convenience, if you already have all the environments tested and working in MuJoCo, there is a overhead in switching. If you are just starting out, I'd recommend an open-source physics engine over MuJoCo. 

I'm closing this issue here. If you have any further questions, you can contact me via email.
